server:
  port: 6060
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smart_signals?user=root&password=jayesh@13&serverTimezone=UTC&useSSL=false
  jpa:
    database: MYSQL
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
